# This file contains OKD-specific configuration for OperatorHub, it needs to be kept in sync 
# with manifests/ and make sure only community-operators catalog is enabled by default
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    capability.openshift.io/name: "marketplace"
spec:
  disableAllDefaultSources: true
  sources:
  - name: "community-operators"
    disabled: false
