kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketplace-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: "marketplace"
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  - operatorhubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resourceNames:
  - marketplace
  resources:
  - clusteroperators/status
  verbs:
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resourceNames:
  - cluster
  resources:
  - operatorhubs/status
  verbs:
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - get
  - list
  - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketplace-operator
  namespace: openshift-marketplace
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: "marketplace"
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - create
  - patch
  - update
  - delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operatorhub-config-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: "marketplace"
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - operatorhubs
  verbs:
  - get
  - list
  - watch
